version: 2

sources: 
  - name: airbnb
    schema: raw
    tables: 
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              # Test to ensure that the COUNT(DISTINCT room_type) is always 4
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4 
          - name: price
            tests: 
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date # Specify the original date name
        # Doc | Freshness: https://docs.getdbt.com/reference/resource-properties/freshness
        # A freshness block is used to define the acceptable amount of time between the most recent record and now, for a 
        # table to be considered "fresh".
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}